"""Runtime primitives for permit-governed external operations."""

from .operation_dispatcher import (
    AdapterProtocol,
    DispatchError,
    Dispatcher,
    OperationPermitStore,
    PermitStateError,
    PermitValidationError,
    claim_permit,
    consume_permit,
    expire_permit,
    issue_permit,
    normalize_payload,
    payload_fingerprint,
    reconcile_claimed_permit,
    revoke_permit,
    transition_permit,
    validate_permit,
)
from .worker_runtime import (
    RUNTIME_REGISTRY,
    RuntimeProfileError,
    RuntimeRequirement,
    WorkerRuntimeProfile,
    WorkerRuntimeRegistry,
    approved_runtime_ids,
    load_runtime_profiles,
    profile_satisfies,
    requirement_for_lane,
    select_runtime,
)

__all__ = [
    "AdapterProtocol",
    "DispatchError",
    "Dispatcher",
    "OperationPermitStore",
    "PermitStateError",
    "PermitValidationError",
    "claim_permit",
    "consume_permit",
    "expire_permit",
    "issue_permit",
    "normalize_payload",
    "payload_fingerprint",
    "reconcile_claimed_permit",
    "revoke_permit",
    "transition_permit",
    "validate_permit",
    "RUNTIME_REGISTRY",
    "RuntimeProfileError",
    "RuntimeRequirement",
    "WorkerRuntimeProfile",
    "WorkerRuntimeRegistry",
    "approved_runtime_ids",
    "load_runtime_profiles",
    "profile_satisfies",
    "requirement_for_lane",
    "select_runtime",
]
